name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use the version specified in your project

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Generate Coverage Report
      run: npm run coverage

    - name: Upload Coverage to Coveralls (optional)
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: npx coveralls < coverage/lcov.info
